version: '3.8'

services:
  mcp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-service
    restart: unless-stopped
    ports:
      - "8000:8000"  # Cambiado de 3000:3000 a 8000:8000 para alinear con el código
    environment:
      - MCP_PROXY_TOKEN=${MCP_PROXY_TOKEN:-test123}
      - PYTHONPATH=${PYTHONPATH:-/app}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - MCP_PORT=${MCP_PORT:-8000}
    volumes:
      - .:/app
    networks:
      - mcp-network
networks:
  mcp-network:
    driver: bridge 