version: '3.8'

services:
  mcp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MCP_PROXY_TOKEN=${MCP_PROXY_TOKEN:-test123}
      - PYTHONPATH=${PYTHONPATH:-/app}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - MCP_PORT=${MCP_PORT:-3000}
    volumes:
      # Volúmenes para desarrollo - comentar en producción
      - ./src:/app/src
      - ./run_server.py:/app/run_server.py
    networks:
      - mcp-network
    depends_on:
      - mcp-inspector

  mcp-inspector:
    image: node:18-alpine
    container_name: mcp-inspector
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MCP_PROXY_TOKEN=${MCP_PROXY_TOKEN:-test123}
    command: >
      sh -c "
        npm install -g @modelcontextprotocol/inspector &&
        mcp-inspector http://mcp-service:3000/sse
      "
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 